# Generated by Django 6.0.5 on 2026-06-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='null', upload_to='covers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('fantasy', 'Fantasy'), ('classics', 'Classics'), ('education', 'Education'), ('children', 'Children'), ('new_arrivals', 'New Arrivals')], max_length=100),
        ),
    ]
