# Generated by Django 6.0.5 on 2026-06-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_cover_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='description', max_length=500),
            preserve_default=False,
        ),
    ]
