# Generated by Django 6.0.5 on 2026-06-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_created_at_alter_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
    ]
