# Generated by Django 6.0.5 on 2026-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('fantasy', 'Fantasy'), ('classics', 'Classics'), ('education', 'Education'), ('children', 'Children')], max_length=100),
        ),
    ]
