# Generated by Django 6.0.5 on 2026-06-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
    ]
