# Generated by Django 6.0.5 on 2026-06-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_comment_author_alter_comment_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
